# Generated by Django 3.2.9 on 2021-11-15 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_datebooked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebooked',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 20, 28, 48, 38497)),
        ),
    ]
