# Generated by Django 3.2.9 on 2021-11-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_alter_datebooked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebooked',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
